// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjzssimbovlmskxdzsoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqenNzaW1ib3ZsbXNreGR6c29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDA4MDIsImV4cCI6MjA2NTQxNjgwMn0.8xddBZduyGbpm7bm4pb1PQtoL3E8TM5baRwhDa8pNUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});