// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yekeuidvfobyyhyktull.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlla2V1aWR2Zm9ieXloeWt0dWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzg5NjMsImV4cCI6MjA3MTk1NDk2M30.UtGw0hRR_zlPiam028ix2RxDaNIIunPjBqZHxFzpesA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});